"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'b@n605*@a59yzz7*mv^zjy(f5q_zkwd^0sl4)0k8k+!wxnpu!t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_jinja',
    'main',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'gn_django.site.middleware.SiteFromDomainMiddleware',
]

ROOT_URLCONF = 'project.urls'

from gn_django.template.loaders import get_multi_hierarchy_loader
TEMPLATE_BASE = os.path.join(BASE_DIR, 'templates')
loader = get_multi_hierarchy_loader(
    "gn_django.site.get_namespace_for_site",
    (
        ('eurogamer_net', (
            ('eurogamer_net', os.path.join(TEMPLATE_BASE, 'eurogamer_net')),
            ('eurogamer', os.path.join(TEMPLATE_BASE, 'eurogamer')),
            ('core', os.path.join(TEMPLATE_BASE, 'core')),
        )),
        ('eurogamer_de', (
            ('eurogamer_de', os.path.join(TEMPLATE_BASE, 'eurogamer_de')),
            ('eurogamer', os.path.join(TEMPLATE_BASE, 'eurogamer')),
            ('core', os.path.join(TEMPLATE_BASE, 'core')),
        )),
        ('vg247_com', (
            ('vg247_com', os.path.join(TEMPLATE_BASE, 'vg247_com')),
            ('vg247', os.path.join(TEMPLATE_BASE, 'vg247')),
            ('core', os.path.join(TEMPLATE_BASE, 'core')),
        )),
        ('vg247_pl', (
            ('vg247_pl', os.path.join(TEMPLATE_BASE, 'vg247_pl')),
            ('vg247', os.path.join(TEMPLATE_BASE, 'vg247')),
            ('core', os.path.join(TEMPLATE_BASE, 'core')),
        )),
    )
)

#STATIC_SITE_DOMAIN = "vg247.com"
SITE_DOMAINS = {
    "127.0.0.1": "eurogamer.net",
    "eurogamer.net.local": "eurogamer.net",
    "eurogamer.de.local": "eurogamer.de",
    "vg247.com.local": "vg247.com",
    "vg247.pl.local": "vg247.pl",
}

SITE_NAMESPACES = {
    "eurogamer.net": "eurogamer_net",
    "eurogamer.de": "eurogamer_de",
    "vg247.com": "vg247_com",
    "vg247.pl": "vg247_pl",
}

TEMPLATES = [
    {
        "BACKEND": "gn_django.template.backend.Jinja2",
        "APP_DIRS": True,
        "OPTIONS": {
            'match_extension': None,
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'gn_django.template.context_processors.settings',
            ],
            'loader': loader,
            'template_cache_key_cb': 'gn_django.site.template.get_template_cache_key_with_site',
        }
    },
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'gn_django.template.context_processors.settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
